export type DashboardModalType =
  | 'addNewMachine'
  | 'batch'
  | 'replenishCoins'
  | 'moreOperation'
  | 'editMachine'
  | 'changeProduct'
  | 'remoteUnlock'
  | 'errorReset'
  | 'securityStatus'
  | 'clawStoreFilter'
  | 'updateStoreFilter'
  | 'coinStoreFilter'
export type ProductListModalType = 'more' | 'add' | 'edit' | 'delete'
export type GroupListModalType = 'add' | 'more' | 'edit' | 'delete'
